// Bold section headers from the reference checklist = parents; the
// lines under each = children. "type: checklist" sections are
// documents to confirm (checkbox per line); "type: fields" sections
// are actual data values to record (text/date input per line).
export const CHECKLIST_SCHEMA = [
  {
    key: "documentation",
    title: "Documentation",
    type: "checklist",
    items: [
      { key: "deed_of_sale", label: "Deed of Sale of Motor Vehicle with Assumption" },
      { key: "acknowledgement_receipt", label: "Acknowledgement Receipt (3 copies)" },
      { key: "authorization_letter", label: "Authorization Letter (5 copies)" },
      { key: "spa", label: "Special Power of Attorney (SPA) (5 copies)" },
      { key: "bir_spa", label: "BIR Special Power of Attorney (SPA) (3 copies)" },
      { key: "driver_exit_clearance", label: "Driver Exit Clearance" },
      { key: "peer_clearance_waiver", label: "Peer Clearance Waiver" },
    ],
  },
  {
    key: "provisional_authority",
    title: "Provisional Authority",
    type: "checklist",
    items: [
      { key: "or_cr", label: "OR or CR" },
      { key: "sales_invoice", label: "Sales Invoice (if no OR/CR yet)" },
      { key: "delivery_note", label: "Delivery Note (if no OR/CR yet)" },
      { key: "valid_ids", label: "2 Valid ID's w/ Signature" },
      { key: "proof_of_citizenship", label: "1 Proof of Citizenship (PSA or Passport)" },
      { key: "marriage_certificate", label: "Marriage Certificate (if Female Owner)" },
      { key: "id_picture", label: "2 2x2 ID Picture" },
      { key: "pro_drivers_license", label: "Pro Driver's License (for Driver)" },
    ],
  },
  {
    key: "certificate_of_public_convenience",
    title: "Certificate of Public Convenience",
    type: "checklist",
    items: [
      { key: "nbi_driver", label: "NBI (driver)" },
      { key: "police_clearance_driver", label: "Police Clearance (driver)" },
      { key: "garage_title", label: "Garage Title" },
      { key: "proof_of_garage", label: "Proof of Garage" },
      { key: "photo_5r_newspaper", label: "5R photo of unit with Newspaper" },
    ],
  },
  {
    key: "renewal",
    title: "Renewal",
    type: "checklist",
    items: [
      { key: "franchise_verification", label: "Franchise Verification" },
      { key: "notarized_application", label: "Notarized Application" },
      { key: "current_lto_or_cr", label: "Current LTO OR & CR" },
      { key: "insurance", label: "Insurance" },
      { key: "dti", label: "DTI" },
      { key: "proof_of_filipino_citizenship", label: "Proof of Filipino Citizenship" },
      { key: "proof_of_existence_garage", label: "Proof of Existence & Sufficiency of Garage" },
      { key: "proof_of_financial_capability", label: "Proof of Financial Capability" },
      { key: "bir_annual_income_tax_return", label: "BIR Annual Income Tax Return" },
    ],
  },
  {
    key: "grab",
    title: "Grab",
    type: "checklist",
    items: [
      { key: "nbi_driver", label: "NBI (driver)" },
      { key: "police_clearance_driver", label: "Police Clearance (driver)" },
      { key: "drug_test_driver", label: "Drug Test (driver)" },
    ],
  },
  {
    key: "vehicle_details",
    title: "Vehicle Details",
    type: "fields",
    items: [
      { key: "owner_first_name", label: "Owner's Name (First)" },
      { key: "owner_middle_name", label: "Owner's Name (Middle)" },
      { key: "owner_last_name", label: "Owner's Name (Last)" },
      { key: "owner_address", label: "Owner's Address" },
      { key: "vehicle_sales_invoice", label: "Vehicle Sales Invoice" },
      { key: "vehicle_delivery_note", label: "Vehicle Delivery Note" },
      { key: "make", label: "Make" },
      { key: "model", label: "Model" },
      { key: "description", label: "Description" },
      { key: "color", label: "Color" },
      { key: "cs_number", label: "CS #" },
      { key: "vin_chassis_number", label: "VIN # / Chassis #" },
      { key: "engine_number", label: "Engine #" },
      { key: "displacement", label: "Displacement" },
      { key: "year_model", label: "Year Model" },
      { key: "gross_weight", label: "Gross Weight" },
      { key: "key_no", label: "Key No." },
      { key: "certificate_of_stock_reported", label: "Certificate of Stock Reported" },
      { key: "downpayment_ack_receipt", label: "Downpayment Acknowledgement Receipt" },
      { key: "insurance_ack_receipt", label: "Insurance Acknowledgement Receipt" },
      { key: "mv_file_number", label: "MV File #" },
    ],
  },
  {
    key: "loan_agency",
    title: "Loan Agency",
    type: "fields",
    items: [
      { key: "bank", label: "Bank" },
      { key: "loan_account_number", label: "Loan Account #" },
      { key: "due_date", label: "Due Date", inputType: "date" },
      { key: "amount_due", label: "Amount Due" },
    ],
  },
  {
    key: "ltms",
    title: "LTMS",
    type: "fields",
    items: [
      { key: "lto_id", label: "LTO ID" },
      { key: "password", label: "Password" },
      { key: "email", label: "Email" },
      { key: "next_renewal", label: "Next Renewal", inputType: "date" },
    ],
  },
];
